services:
  money-tracker-ui:
    container_name: clematis-money-tracker-ui
    image: money.tracker.ui.uat:latest
    ports:
      - '18081:80'
      - '18443:443'
    volumes:
      - "nginx-default.conf:/etc/nginx/conf.d/default.conf"
      - ssl_certs:/usr/local/openresty/nginx/ssl:ro
    networks:
      - clematis
    restart: unless-stopped

  money-tracker-ui-demo:
    container_name: clematis-money-tracker-ui-demo
    image: money.tracker.ui.demo:latest
    ports:
      - '18082:80'
      - '18444:443'
    volumes:
      - "nginx-demo.conf:/etc/nginx/conf.d/default.conf"
      - ssl_certs:/usr/local/openresty/nginx/ssl:ro
    networks:
      - clematis
    restart: unless-stopped

volumes:
  ssl_certs:
    name: jenkins_ssl_certs    # the external volume name
    external: true

networks:
  clematis:
    driver: bridge
