version: '3.9'
services:
  money-tracker-ui:
    container_name: clematis-money-tracker-ui
    image: money.tracker.ui.uat:latest
    ports:
      - '18081:80'
      - '18443:443'
    volumes:
      - /home/clematis/mt-ui/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ssl_certs:/etc/nginx/ssl:ro
    networks:
      - clematis
    restart: unless-stopped

  money-tracker-ui-demo:
    container_name: clematis-money-tracker-ui-demo
    image: money.tracker.ui.demo:latest
    ports:
      - '18082:80'
    volumes:
      - /home/clematis/mt-ui/nginx-demo.conf:/etc/nginx/conf.d/default.conf
    networks:
      - clematis
    restart: unless-stopped

volumes:
  ssl_certs:

networks:
  clematis:
    driver: bridge
