version: '3.9'
services:

  money_tracker_ui:
    container_name: clematis-money-tracker-ui
    image: money.tracker.ui:latest
    networks:
      - clematis_mt
    ports:
      - "18081:80"
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure

networks:
  clematis_mt:
    driver: bridge

