version: '3.9'
services:

  money-tracker-ui:
    container_name: clematis-money-tracker-ui
    image: money.tracker.ui:latest
    ports:
      - "18081:80"
    networks:
      - clematis
    restart: unless-stopped

networks:
  clematis:
    driver: bridge
